mainfile_hogwartz/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('logout', 'Auth\LoginController@logout')->name('logout');
Route::group(['middleware' => 'guest'], function () {
    Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('login', 'Auth\LoginController@login');
    Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
    Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('reset');
    Route::post('password/reset', 'Auth\ResetPasswordController@reset');
});

Route::get('/', 'FHomeController@index')->name('front.index');
$all_langs = config('app.all_langs');
foreach ($all_langs as $prefix) {
    Route::group(['prefix' => $prefix, 'middleware' => 'configcookieslang'], function () use ($prefix) {
        Route::get('/', 'FIndexController@index');
        Route::get(\Lang::get('route.about', [], $prefix), 'FAboutController@index');
        Route::get(\Lang::get('route.confirmation', [], $prefix), 'FConfirmationController@index');
        Route::get(\Lang::get('route.reservation', [], $prefix), 'FReservationController@index');
        Route::get(\Lang::get('route.schedule', [], $prefix), 'FScheduleController@index');
        Route::get(\Lang::get('route.schedule', [], $prefix) . '/{slug}', 'FScheduleController@detail');
        Route::get(\Lang::get('route.outlet', [], $prefix), 'FOutletController@index');
        Route::post(\Lang::get('route.outlet', [], $prefix) . '/onlineorder', 'FOutletController@onlineorder');
        Route::get(\Lang::get('route.outlet', [], $prefix) . '/{slug}', 'FOutletController@detail');
        Route::get(\Lang::get('route.package', [], $prefix) . '/{slug}', 'FPackageController@index');
        Route::get(\Lang::get('route.menu', [], $prefix), 'FMenusController@index');
        Route::get(\Lang::get('route.news', [], $prefix), 'FNewsFeedController@index');
        Route::get(\Lang::get('route.news', [], $prefix) . '/{slug}', 'FNewsFeedController@detail');
        Route::get(\Lang::get('route.news', [], $prefix) . '/category/{slug}', 'FNewsFeedController@category');
        Route::get(\Lang::get('route.news', [], $prefix) . '/tag/{slug}', 'FNewsFeedController@tag');
        Route::get(\Lang::get('route.news', [], $prefix) . '/archive/{thbln}', 'FNewsFeedController@archive');
        Route::get(\Lang::get('route.sistercompany', [], $prefix), 'FSisterCompanyController@index');
        Route::get(\Lang::get('route.contact', [], $prefix), 'FContactController@index');
        Route::post(\Lang::get('route.contact', [], $prefix), 'FContactController@store');
        Route::post(\Lang::get('route.contact', [], $prefix) . '/getdataoutlet', 'FContactController@outlet');
        Route::get(\Lang::get('route.contact', [], $prefix) . '/getdataoutlet', 'FContactController@outletwithoutloc');
        Route::post('online-order', 'FOnlineOrderController@store');
        Route::post('online-order-form', 'FOnlineOrderController@storeReservation');
        Route::post('confirmation-send', 'FConfirmationController@store');
        Route::post('confirmation-send', 'FConfirmationController@store');
        Route::get(\Lang::get('route.gallery', [], $prefix), 'FGalleryController@index');
        Route::get(\Lang::get('route.gallery', [], $prefix) . '/{slug}', 'FGalleryController@detail');
    });
}
Route::get('homeslider', 'FIndexController@homeslider');
Route::get('sitemap.xml', 'FSiteMapController@siteMapRobot');
Route::get('test-email', "FOnlineOrderController@tryEmail");

Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {
    Route::get('/', ['as' => 'admin.index', 'uses' => 'HomeController@index']);
    Route::resource('email', 'BEmailController', ['except' => 'show']);
    Route::resource('social-link', 'BSocialController', ['except' => 'show']);
    Route::resource('user', 'BAdminController', ['only' => [
        'index', 'create', 'store', 'destroy'
    ]]);
    Route::post('contact-messages/confirm', ['as' => 'contact-messages.confirm', 'uses' => 'BContactController@confirm']);
    Route::resource('contact-messages', 'BContactController', ['only' => [
        'index', 'destroy'
    ]]);
    Route::get('changepassword', 'BUserController@password');
    Route::post('changepassword', 'BUserController@updatepassword');
    Route::get('menu-utama', ['as' => 'menu-utama.index', 'uses' => 'BMenuUtamaController@index']);
    Route::get('menu-utama/{id}/edit', ['as' => 'menu-utama.edit', 'uses' => 'BMenuUtamaController@edit']);
    Route::patch('menu-utama/{id}', ['as' => 'menu-utama.update', 'uses' => 'BMenuUtamaController@update']);

    Route::get('footer/{id}/edit', ['as' => 'footer.edit', 'uses' => 'BFooterController@edit']);
    Route::patch('footer/{id}', ['as' => 'footer.update', 'uses' => 'BFooterController@update']);

    Route::get('online-order', ['as' => 'onlineorder.index', 'uses' => 'BOnlineOrderController@index']);
    Route::get('online-order/{id}/edit', ['as' => 'onlineorder.edit', 'uses' => 'BOnlineOrderController@edit']);
    Route::patch('online-order/{id}', ['as' => 'onlineorder.update', 'uses' => 'BOnlineOrderController@update']);
    Route::delete('online-order/{id}', ['as' => 'onlineorder.destroy', 'uses' => 'BOnlineOrderController@destroy']);

    Route::get('web-config', ['as' => 'web-config.index', 'uses' => 'BWebConfigController@index']);
    Route::patch('web-config', ['as' => 'web-config.update', 'uses' => 'BWebConfigController@update']);

    Route::get('filemanager', ['as' => 'filemanager.index', 'uses' => 'BWebConfigController@filemanager']);

    //homeslider
    Route::get('config/homeslider', ['as' => 'admin.config.homeslider.index', 'uses' => 'BHomeSliderController@index']);
    Route::get('config/homeslider/create', ['as' => 'admin.config.homeslider.create', 'uses' => 'BHomeSliderController@create']);
    Route::post('config/homeslider', ['as' => 'admin.config.homeslider.store', 'uses' => 'BHomeSliderController@store']);
    Route::get('config/homeslider/{id}/edit', ['as' => 'admin.config.homeslider.edit', 'uses' => 'BHomeSliderController@edit']);
    Route::patch('config/homeslider/{id}', ['as' => 'admin.config.homeslider.update', 'uses' => 'BHomeSliderController@update']);
    Route::post('config/homeslider/destroy', ['as' => 'admin.config.homeslider.destroy', 'uses' => 'BHomeSliderController@destroy']);

    //homekonten
    Route::get('config/home-konten', ['as' => 'admin.config.home-konten.index', 'uses' => 'BHomeKontenController@index']);
    //specialities
    Route::get('config/home-konten/specialities/create', ['as' => 'specialities.create', 'uses' => 'BSpecialitiesController@create']);
    Route::post('config/home-konten/specialities', ['as' => 'specialities.store', 'uses' => 'BSpecialitiesController@store']);
    Route::get('config/home-konten/specialities/{id}/edit', ['as' => 'specialities.edit', 'uses' => 'BSpecialitiesController@edit']);
    Route::patch('config/home-konten/specialities/{id}', ['as' => 'specialities.update', 'uses' => 'BSpecialitiesController@update']);
    Route::delete('config/home-konten/specialities/{equal_id}', ['as' => 'specialities.destroy', 'uses' => 'BSpecialitiesController@destroy']);

    Route::patch('discover/{id}', ['as' => 'discover.update', 'uses' => 'BHomeKontenController@updateDiscover']);

    Route::patch('config/dsimage', ['as' => 'dsimage.update', 'uses' => 'BHomeKontenController@updateDsImage']);

    //Services
    Route::get('config/home-konten/services/create', ['as' => 'services.create', 'uses' => 'BServiceController@create']);
    Route::post('config/home-konten/services', ['as' => 'services.store', 'uses' => 'BServiceController@store']);
    Route::get('config/home-konten/services/{id}/edit', ['as' => 'services.edit', 'uses' => 'BServiceController@edit']);
    Route::patch('config/home-konten/services/{id}', ['as' => 'services.update', 'uses' => 'BServiceController@update']);
    Route::delete('config/home-konten/services/{equal_id}', ['as' => 'services.destroy', 'uses' => 'BServiceController@destroy']);

    //Testimonial
    Route::get('config/home-konten/testimonial/create', ['as' => 'testimonial.create', 'uses' => 'BTestimonialController@create']);
    Route::post('config/home-konten/testimonial', ['as' => 'testimonial.store', 'uses' => 'BTestimonialController@store']);
    Route::get('config/home-konten/testimonial/{id}/edit', ['as' => 'testimonial.edit', 'uses' => 'BTestimonialController@edit']);
    Route::patch('config/home-konten/testimonial/{id}', ['as' => 'testimonial.update', 'uses' => 'BTestimonialController@update']);
    Route::delete('config/home-konten/testimonial/{equal_id}', ['as' => 'testimonial.destroy', 'uses' => 'BTestimonialController@destroy']);

    //package recomended
    Route::get('config/packages/createRecommend', ['as' => 'packages.createRecommend', 'uses' => 'BPackagesController@createRecommend']);
    Route::post('config/packages/updateRecommend', ['as' => 'packages.updateRecommend', 'uses' => 'BPackagesController@updateRecommend']);
    Route::delete('config/packages/destroyRecommend/{id}', ['as' => 'packages.destroyRecommend', 'uses' => 'BPackagesController@destroyRecommend']);

    //menus recomended
    Route::get('config/menus/createRecommend', ['as' => 'menus.createRecommend', 'uses' => 'BMenusController@createRecommend']);
    Route::post('config/menus/updateRecommend', ['as' => 'menus.updateRecommend', 'uses' => 'BMenusController@updateRecommend']);

mainfile_hogwartz/app/Outlet.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Outlet extends Model
{
    protected $primaryKey = 'id';
    protected $guarded = [];
    protected $table = 'outlet';

    public function getPageHeaderAttribute()
    {
        if ($this->image !== '') {
            return asset('assets/front/images/' . $this->image);
        } else {
            return 'http://placehold.it/1129x306';
        }
    }

    public function getHomeSliderAttribute()
    {
        if ($this->image !== '') {
            return asset('assets/front/images/' . $this->image);
        } else {
            return 'http://placehold.it/1920x1080';
        }
    }

    public function getPartnerImageAttribute()
    {
        if ($this->image !== '') {
            return asset('assets/front/images/' . $this->image);
        } else {
            return 'http://placehold.it/176x108';
        }
    }

    public function images() {
        return $this->hasMany('App\Images', 'outlet_id');
    }

    public function order() {
        return $this->hasMany('App\OnlineOrder', 'outlet_id');
    }

    public function contact_messages() {
        return $this->hasMany('App\ContactMessages', 'outlet_id');
    }

    public function menus() {
        return $this->belongsToMany('App\Menus', 'menu_outlet', 'outlet_id', 'menu_id')->withTimestamps();
    }
}

mainfile_hogwartz/app/WebConfig.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class WebConfig extends Model
{
    protected $table = 'web_config';
    protected $fillable = [
        'config_name', 'value',
    ];
}

mainfile_hogwartz/resources/views/admin/webconfig/outlet/create.blade.php
@extends('layouts.back')

@section('page-level-style')
    <link href="{{ asset('assets/back/global/plugins/bootstrap-fileinput/bootstrap-fileinput.css') }}" rel="stylesheet" type="text/css" />
@endsection

@section('page-js-plugin')
    <script src="{{ asset('assets/back/global/plugins/bootstrap-fileinput/bootstrap-fileinput.js') }}" type="text/javascript"></script>
@endsection

@section('custom-js')
@include('admin._editor_textarea_init')
  
@endsection

@section('page-heading')
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <span>Web Connection</span>
                <i class="fa fa-circle"></i>
            </li>
            <li>
                <a href="{{ route('menu-utama.index') }}"><span>Manage Main Menu</span></a>
                <i class="fa fa-circle"></i>
            </li>
            
            <li>
                <a href="{{ route('admin.config.outlet.index') }}"><span>Manage Outlet</span></a>
                <i class="fa fa-circle"></i>
            </li>
            <li>
               <span>Add Outlet</span>
              
            </li>
        </ul>
    </div>
    <h3 class="page-title"> Add Outlet</h3>
@endsection

@section('conten')
    <div class="row">
        <div class="col-md-12">
            <div class="portlet light bordered" style="display: block; overflow:auto;">
                <div class="portlet-title">
                    <div class="caption font-dark">
                        <span class="caption-subject bold uppercase"> Add Bebek Bengil Outlet</span>
                    </div>
                </div>
                <div class="portlet-body">
                 {!! Form::open(['route' => ['outlet.store'], 'files' => true, 'id' => 'submit_form', 'novalidate'])!!}
                  
                    @foreach(config('app.all_langs') as $lang)
                        <div class="form-group {!! $errors->has('title_'.$lang) ? 'has-error' : '' !!}">
                            {!! Form::label('title_'.$lang, 'Title ('.config('app.human_langs')[$lang].')') !!}
                            {!! Form::text('title_'.$lang, null, ['class'=>'form-control', 'required']) !!}
                            {!! $errors->first('title_'.$lang, '<p class="help-block">:message</p>') !!}
                        </div>
                    @endforeach

                    <div class="form-group {!! $errors->has('email') ? 'has-error' : '' !!}">
                        {!! Form::label('email', 'Email Recipient') !!}
                        {!! Form::text('email', null, ['class'=>'form-control', 'required']) !!}
                        {!! $errors->first('email', '<p class="help-block">:message</p>') !!}
                    </div>
                
                    @foreach(config('app.all_langs') as $lang)
                        <div class="form-group {!! $errors->has('description_'.$lang) ? 'has-error' : '' !!}">
                            {!! Form::label('description_'.$lang, 'Description ('.config('app.human_langs')[$lang].')') !!}
                            {!! Form::textarea('description_'.$lang, null, ['class'=>'form-control editor-textarea','size' => '30x5']) !!}
                            {!! $errors->first('description_'.$lang, '<p class="help-block">:message</p>') !!}
                        </div>
                    @endforeach

                     <div class="form-group {!! $errors->has('image') ? 'has-error' : '' !!}" >
                        {!! Form::label('image', 'Image (jpeg, png)') !!}
                        <div class="row col-md-12" style="margin-bottom: 20px;">
                            <div class="fileinput fileinput-new" data-provides="fileinput">
                                <div class="fileinput-new thumbnail" style="width: 280px; height: 170px;">
                                    <img src="http://www.placehold.it/280x170/EFEFEF/AAAAAA&amp;text=no+image" alt="" /> </div>
                                <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;"> </div>
                                <div>
                                                        <span class="btn default btn-file">
                                                            <span class="fileinput-new"> Select image </span>
                                                            <span class="fileinput-exists"> Change </span>
                                                            {!! Form::file('image', ['required']) !!} </span>
                                    <a href="javascript:;" class="btn red fileinput-exists" data-dismiss="fileinput"> Remove </a>
                                </div>
                            </div>
                            {!! $errors->first('image', '<p class="help-block">:message</p>') !!}
                        </div>
                    </div>

                    <div class="form-group {!! $errors->has('lat') ? 'has-error' : '' !!}">
                        {!! Form::label('lat', 'Latitude') !!}
                        {!! Form::text('lat', null, ['class'=>'form-control', 'required']) !!}
                        {!! $errors->first('lat', '<p class="help-block">:message</p>') !!}
                    </div>

                    <div class="form-group {!! $errors->has('long') ? 'has-error' : '' !!}">
                        {!! Form::label('long', 'Longitude') !!}
                        {!! Form::text('long', null, ['class'=>'form-control', 'required']) !!}
                        {!! $errors->first('long', '<p class="help-block">:message</p>') !!}
                    </div>

                    @foreach(config('app.all_langs') as $lang)
                        <div class="form-group {!! $errors->has('address_info_'.$lang) ? 'has-error' : '' !!}">
                            {!! Form::label('address_info_'.$lang, 'Address Information ('.config('app.human_langs')[$lang].')') !!}
                            {!! Form::textarea('address_info_'.$lang, null, ['class'=>'form-control editor-textarea','rows' => '4']) !!}
                            {!! $errors->first('address_info_'.$lang, '<p class="help-block">:message</p>') !!}
                        </div>
                    @endforeach

                    @foreach(config('app.all_langs') as $lang)
                        <div class="form-group {!! $errors->has('meta_title_'.$lang) ? 'has-error' : '' !!}">
                            {!! Form::label('meta_title_'.$lang, 'Meta Title ('.config('app.human_langs')[$lang].')') !!}
                            {!! Form::text('meta_title_'.$lang, null, ['class'=>'form-control']) !!}
                            {!! $errors->first('meta_title_'.$lang, '<p class="help-block">:message</p>') !!}
                        </div>
                        <div class="form-group {!! $errors->has('meta_keyword_'.$lang) ? 'has-error' : '' !!}">
                            {!! Form::label('meta_keyword_'.$lang, 'Meta Keyword ('.config('app.human_langs')[$lang].')') !!}
                            {!! Form::text('meta_keyword_'.$lang, null, ['class'=>'form-control']) !!}
                            {!! $errors->first('meta_keyword_'.$lang, '<p class="help-block">:message</p>') !!}
                        </div>
                        <div class="form-group {!! $errors->has('meta_description_'.$lang) ? 'has-error' : '' !!}">
                            {!! Form::label('meta_description_'.$lang, 'Meta Description ('.config('app.human_langs')[$lang].')') !!}
                            {!! Form::textarea('meta_description_'.$lang, null, ['class'=>'form-control', 'rows' => '3']) !!}
                            {!! $errors->first('meta_description_'.$lang, '<p class="help-block">:message</p>') !!}
                        </div>
                    @endforeach

                    <div class="row col-md-12">
                        <hr>
                        <div class="text-right">
                            {!! Form::submit('Save', ['class'=>'btn btn-primary']) !!}
                        </div>
                    </div>
                    {!! Form::close() !!}
                </div>
            </div>
            <!-- END EXAMPLE TABLE PORTLET-->
        </div>
    </div>
@endsection

mainfile_hogwartz/resources/views/admin/webconfig/outlet/edit.blade.php
@extends('layouts.back')

@section('page-level-style')
    <link href="{{ asset('assets/back/global/plugins/bootstrap-fileinput/bootstrap-fileinput.css') }}" rel="stylesheet" type="text/css" />
@endsection

@section('page-js-plugin')
    <script src="{{ asset('assets/back/global/plugins/bootstrap-fileinput/bootstrap-fileinput.js') }}" type="text/javascript"></script>
@endsection

@section('custom-js')
   @include('admin._editor_textarea_init')
@endsection

@section('page-heading')
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <span>Web Connection</span>
                <i class="fa fa-circle"></i>
            </li>
            <li>
                <a href="{{ route('menu-utama.index') }}"><span>Manage Main Menu</span></a>
                <i class="fa fa-circle"></i>
            </li>
            
            <li>
                <a href="{{ route('admin.config.outlet.index') }}"><span>Manage Outlet</span></a>
                <i class="fa fa-circle"></i>
            </li>
            <li>
               <span>Edit Outlet </span>
              
            </li>
        </ul>
    </div>
    <h3 class="page-title"> Edit Outlet</h3>
@endsection

@section('conten')
    <div class="row">
        <div class="col-md-12">
            <div class="portlet light bordered" style="display: block; overflow:auto;">
                <div class="portlet-title">
                    <div class="caption font-dark">
                        <span class="caption-subject bold uppercase"> Edit Bebek Bengil Outlet</span>
                    </div>
                </div>
                <div class="portlet-body">
                 {!! Form::open(['route' => ['outlet.update', $outlet->first()->equal_id], 'method' => 'patch', 'files' => true, 'id' => 'submit_form', 'novalidate'])!!}
                  
                    @foreach(config('app.all_langs') as $lang)
                        <div class="form-group {!! $errors->has('title_'.$lang) ? 'has-error' : '' !!}">
                            {!! Form::label('title_'.$lang, 'Outlet title ('.config('app.human_langs')[$lang].')') !!}
                            {!! Form::text('title_'.$lang, $outlet->where('lang', $lang)->first()->title, ['class'=>'form-control', 'required']) !!}
                            {!! $errors->first('title_'.$lang, '<p class="help-block">:message</p>') !!}
                        </div>
                    @endforeach

                    <div class="form-group {!! $errors->has('email') ? 'has-error' : '' !!}">
                        {!! Form::label('email', 'Email Recipient') !!}
                        {!! Form::text('email', $outlet->first()->email, ['class'=>'form-control', 'required']) !!}
                        {!! $errors->first('email', '<p class="help-block">:message</p>') !!}
                    </div>

                    @foreach(config('app.all_langs') as $lang)
                        <div class="form-group {!! $errors->has('description_'.$lang) ? 'has-error' : '' !!}">
                            {!! Form::label('description_'.$lang, 'Outlet description ('.config('app.human_langs')[$lang].')') !!}
                            {!! Form::textarea('description_'.$lang, $outlet->where('lang',$lang)->first()->description, ['class'=>'form-control editor-textarea','size' => '30x5']) !!}
                            {!! $errors->first('description_'.$lang, '<p class="help-block">:message</p>') !!}
                        </div>
                    @endforeach

                     <div class="form-group {!! $errors->has('image') ? 'has-error' : '' !!}">
                        {!! Form::label('image', 'Image (jpeg, png)') !!}
                        {!! Form::file('image') !!}
                        {!! $errors->first('image', '<p class="help-block">:message</p>') !!}
                        @if (!empty($outlet->first()) && $outlet->first()->image !== '')
                            <div class="row" style="margin-top: 15px;">
                                <div class="col-md-8">
                                    <p style="margin: 5px 0;">Current Image:</p>
                                    <div class="thumbnail">
                                        <img src="{{ $outlet->first()->home_slider }}" class="img-rounded">
                                    </div>
                                </div>
                            </div>
                        @endif
                    </div>

                    <div class="form-group {!! $errors->has('lat') ? 'has-error' : '' !!}">
                        {!! Form::label('lat', 'Latitude') !!}
                        {!! Form::text('lat', $outlet->first()->lat, ['class'=>'form-control', 'required']) !!}
                        {!! $errors->first('lat', '<p class="help-block">:message</p>') !!}
                    </div>

                    <div class="form-group {!! $errors->has('long') ? 'has-error' : '' !!}">
                        {!! Form::label('long', 'Longitude') !!}
                        {!! Form::text('long', $outlet->first()->lng, ['class'=>'form-control', 'required']) !!}
                        {!! $errors->first('long', '<p class="help-block">:message</p>') !!}
                    </div>

                    @foreach(config('app.all_langs') as $lang)
                        <div class="form-group {!! $errors->has('address_info_'.$lang) ? 'has-error' : '' !!}">
                            {!! Form::label('address_info_'.$lang, 'Address Information ('.config('app.human_langs')[$lang].')') !!}
                            {!! Form::textarea('address_info_'.$lang, $outlet->where('lang',$lang)->first()->address_info, ['class'=>'form-control editor-textarea','rows' => '4']) !!}
                            {!! $errors->first('address_info_'.$lang, '<p class="help-block">:message</p>') !!}
                        </div>
                    @endforeach

                    @foreach(config('app.all_langs') as $lang)
                        <div class="form-group {!! $errors->has('meta_title_'.$lang) ? 'has-error' : '' !!}">
                            {!! Form::label('meta_title_'.$lang, 'Meta Title ('.config('app.human_langs')[$lang].')') !!}
                            {!! Form::text('meta_title_'.$lang, $outlet->where('lang',$lang)->first()->meta_title, ['class'=>'form-control']) !!}
                            {!! $errors->first('meta_title_'.$lang, '<p class="help-block">:message</p>') !!}
                        </div>
                        <div class="form-group {!! $errors->has('meta_keyword_'.$lang) ? 'has-error' : '' !!}">
                            {!! Form::label('meta_keyword_'.$lang, 'Meta Keyword ('.config('app.human_langs')[$lang].')') !!}
                            {!! Form::text('meta_keyword_'.$lang, $outlet->where('lang',$lang)->first()->meta_keyword, ['class'=>'form-control']) !!}
                            {!! $errors->first('meta_keyword_'.$lang, '<p class="help-block">:message</p>') !!}
                        </div>
                        <div class="form-group {!! $errors->has('meta_description_'.$lang) ? 'has-error' : '' !!}">
                            {!! Form::label('meta_description_'.$lang, 'Meta Description ('.config('app.human_langs')[$lang].')') !!}
                            {!! Form::textarea('meta_description_'.$lang, $outlet->where('lang',$lang)->first()->meta_description, ['class'=>'form-control', 'rows' => '3']) !!}
                            {!! $errors->first('meta_description_'.$lang, '<p class="help-block">:message</p>') !!}
                        </div>
                    @endforeach

                    <div class="row col-md-12">
                        <hr>
                        <div class="text-right">
                            {!! Form::submit('Save', ['class'=>'btn btn-primary']) !!}
                        </div>
                    </div>
                    {!! Form::close() !!}
                </div>
            </div>
            <!-- END EXAMPLE TABLE PORTLET-->
        </div>
    </div>
@endsection