mainfile_hogwartz/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('logout', 'Auth\LoginController@logout')->name('logout');
Route::group(['middleware' => 'guest'], function () {
    Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('login', 'Auth\LoginController@login');
    Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
    Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('reset');
    Route::post('password/reset', 'Auth\ResetPasswordController@reset');
});

Route::get('/', 'FHomeController@index')->name('front.index');
$all_langs = config('app.all_langs');
foreach ($all_langs as $prefix) {
    Route::group(['prefix' => $prefix, 'middleware' => 'configcookieslang'], function () use ($prefix) {
        Route::get('/', 'FIndexController@index');
        Route::get(\Lang::get('route.about', [], $prefix), 'FAboutController@index');
        Route::get(\Lang::get('route.confirmation', [], $prefix), 'FConfirmationController@index');
        Route::get(\Lang::get('route.reservation', [], $prefix), 'FReservationController@index');
        Route::get(\Lang::get('route.schedule', [], $prefix), 'FScheduleController@index');
        Route::get(\Lang::get('route.schedule', [], $prefix) . '/{slug}', 'FScheduleController@detail');
        Route::get(\Lang::get('route.outlet', [], $prefix), 'FOutletController@index');
        Route::post(\Lang::get('route.outlet', [], $prefix) . '/onlineorder', 'FOutletController@onlineorder');
        Route::get(\Lang::get('route.outlet', [], $prefix) . '/{slug}', 'FOutletController@detail');
        Route::get(\Lang::get('route.package', [], $prefix) . '/{slug}', 'FPackageController@index');
        Route::get(\Lang::get('route.menu', [], $prefix), 'FMenusController@index');
        Route::get(\Lang::get('route.news', [], $prefix), 'FNewsFeedController@index');
        Route::get(\Lang::get('route.news', [], $prefix) . '/{slug}', 'FNewsFeedController@detail');
        Route::get(\Lang::get('route.news', [], $prefix) . '/category/{slug}', 'FNewsFeedController@category');
        Route::get(\Lang::get('route.news', [], $prefix) . '/tag/{slug}', 'FNewsFeedController@tag');
        Route::get(\Lang::get('route.news', [], $prefix) . '/archive/{thbln}', 'FNewsFeedController@archive');
        Route::get(\Lang::get('route.sistercompany', [], $prefix), 'FSisterCompanyController@index');
        Route::get(\Lang::get('route.contact', [], $prefix), 'FContactController@index');
        Route::post(\Lang::get('route.contact', [], $prefix), 'FContactController@store');
        Route::post(\Lang::get('route.contact', [], $prefix) . '/getdataoutlet', 'FContactController@outlet');
        Route::get(\Lang::get('route.contact', [], $prefix) . '/getdataoutlet', 'FContactController@outletwithoutloc');
        Route::post('online-order', 'FOnlineOrderController@store');
        Route::post('online-order-form', 'FOnlineOrderController@storeReservation');
        Route::post('confirmation-send', 'FConfirmationController@store');
        Route::post('confirmation-send', 'FConfirmationController@store');
        Route::get(\Lang::get('route.gallery', [], $prefix), 'FGalleryController@index');
        Route::get(\Lang::get('route.gallery', [], $prefix) . '/{slug}', 'FGalleryController@detail');
    });
}
Route::get('homeslider', 'FIndexController@homeslider');
Route::get('sitemap.xml', 'FSiteMapController@siteMapRobot');
Route::get('test-email', "FOnlineOrderController@tryEmail");

Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {
    Route::get('/', ['as' => 'admin.index', 'uses' => 'HomeController@index']);
    Route::resource('email', 'BEmailController', ['except' => 'show']);
    Route::resource('social-link', 'BSocialController', ['except' => 'show']);
    Route::resource('user', 'BAdminController', ['only' => [
        'index', 'create', 'store', 'destroy'
    ]]);
    Route::post('contact-messages/confirm', ['as' => 'contact-messages.confirm', 'uses' => 'BContactController@confirm']);
    Route::resource('contact-messages', 'BContactController', ['only' => [
        'index', 'destroy'
    ]]);
    Route::get('changepassword', 'BUserController@password');
    Route::post('changepassword', 'BUserController@updatepassword');
    Route::get('menu-utama', ['as' => 'menu-utama.index', 'uses' => 'BMenuUtamaController@index']);
    Route::get('menu-utama/{id}/edit', ['as' => 'menu-utama.edit', 'uses' => 'BMenuUtamaController@edit']);
    Route::patch('menu-utama/{id}', ['as' => 'menu-utama.update', 'uses' => 'BMenuUtamaController@update']);

    Route::get('footer/{id}/edit', ['as' => 'footer.edit', 'uses' => 'BFooterController@edit']);
    Route::patch('footer/{id}', ['as' => 'footer.update', 'uses' => 'BFooterController@update']);

    Route::get('online-order', ['as' => 'onlineorder.index', 'uses' => 'BOnlineOrderController@index']);
    Route::get('online-order/{id}/edit', ['as' => 'onlineorder.edit', 'uses' => 'BOnlineOrderController@edit']);
    Route::patch('online-order/{id}', ['as' => 'onlineorder.update', 'uses' => 'BOnlineOrderController@update']);
    Route::delete('online-order/{id}', ['as' => 'onlineorder.destroy', 'uses' => 'BOnlineOrderController@destroy']);

    Route::get('web-config', ['as' => 'web-config.index', 'uses' => 'BWebConfigController@index']);
    Route::patch('web-config', ['as' => 'web-config.update', 'uses' => 'BWebConfigController@update']);

    Route::get('filemanager', ['as' => 'filemanager.index', 'uses' => 'BWebConfigController@filemanager']);

    //homeslider
    Route::get('config/homeslider', ['as' => 'admin.config.homeslider.index', 'uses' => 'BHomeSliderController@index']);
    Route::get('config/homeslider/create', ['as' => 'admin.config.homeslider.create', 'uses' => 'BHomeSliderController@create']);
    Route::post('config/homeslider', ['as' => 'admin.config.homeslider.store', 'uses' => 'BHomeSliderController@store']);
    Route::get('config/homeslider/{id}/edit', ['as' => 'admin.config.homeslider.edit', 'uses' => 'BHomeSliderController@edit']);
    Route::patch('config/homeslider/{id}', ['as' => 'admin.config.homeslider.update', 'uses' => 'BHomeSliderController@update']);
    Route::post('config/homeslider/destroy', ['as' => 'admin.config.homeslider.destroy', 'uses' => 'BHomeSliderController@destroy']);

    //homekonten
    Route::get('config/home-konten', ['as' => 'admin.config.home-konten.index', 'uses' => 'BHomeKontenController@index']);
    //specialities
    Route::get('config/home-konten/specialities/create', ['as' => 'specialities.create', 'uses' => 'BSpecialitiesController@create']);
    Route::post('config/home-konten/specialities', ['as' => 'specialities.store', 'uses' => 'BSpecialitiesController@store']);
    Route::get('config/home-konten/specialities/{id}/edit', ['as' => 'specialities.edit', 'uses' => 'BSpecialitiesController@edit']);
    Route::patch('config/home-konten/specialities/{id}', ['as' => 'specialities.update', 'uses' => 'BSpecialitiesController@update']);
    Route::delete('config/home-konten/specialities/{equal_id}', ['as' => 'specialities.destroy', 'uses' => 'BSpecialitiesController@destroy']);

    Route::patch('discover/{id}', ['as' => 'discover.update', 'uses' => 'BHomeKontenController@updateDiscover']);

    Route::patch('config/dsimage', ['as' => 'dsimage.update', 'uses' => 'BHomeKontenController@updateDsImage']);

    //Services
    Route::get('config/home-konten/services/create', ['as' => 'services.create', 'uses' => 'BServiceController@create']);
    Route::post('config/home-konten/services', ['as' => 'services.store', 'uses' => 'BServiceController@store']);
    Route::get('config/home-konten/services/{id}/edit', ['as' => 'services.edit', 'uses' => 'BServiceController@edit']);
    Route::patch('config/home-konten/services/{id}', ['as' => 'services.update', 'uses' => 'BServiceController@update']);
    Route::delete('config/home-konten/services/{equal_id}', ['as' => 'services.destroy', 'uses' => 'BServiceController@destroy']);

    //Testimonial
    Route::get('config/home-konten/testimonial/create', ['as' => 'testimonial.create', 'uses' => 'BTestimonialController@create']);
    Route::post('config/home-konten/testimonial', ['as' => 'testimonial.store', 'uses' => 'BTestimonialController@store']);
    Route::get('config/home-konten/testimonial/{id}/edit', ['as' => 'testimonial.edit', 'uses' => 'BTestimonialController@edit']);
    Route::patch('config/home-konten/testimonial/{id}', ['as' => 'testimonial.update', 'uses' => 'BTestimonialController@update']);
    Route::delete('config/home-konten/testimonial/{equal_id}', ['as' => 'testimonial.destroy', 'uses' => 'BTestimonialController@destroy']);

    //package recomended
    Route::get('config/packages/createRecommend', ['as' => 'packages.createRecommend', 'uses' => 'BPackagesController@createRecommend']);
    Route::post('config/packages/updateRecommend', ['as' => 'packages.updateRecommend', 'uses' => 'BPackagesController@updateRecommend']);
    Route::delete('config/packages/destroyRecommend/{id}', ['as' => 'packages.destroyRecommend', 'uses' => 'BPackagesController@destroyRecommend']);

    //menus recomended
    Route::get('config/menus/createRecommend', ['as' => 'menus.createRecommend', 'uses' => 'BMenusController@createRecommend']);
    Route::post('config/menus/updateRecommend', ['as' => 'menus.updateRecommend', 'uses' => 'BMenusController@updateRecommend']);

mainfile_hogwartz/app/OnlineOrder.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class OnlineOrder extends Model
{
    protected $primaryKey = 'id';
    protected $guarded = [];
    protected $table = 'online_order';

    public static function statusList()
    {
        return [
            'waiting-confirmation' => 'Waiting Confirmation',
            'confirmed' => 'Confirmed',
            'complete' => 'Completed'
        ];
    }

    public static function statusLabel()
    {
        return [
            'waiting-confirmation' => 'label-warning',
            'confirmed' => 'label-info',
            'complete' => 'label-success'
        ];
    }

    public function getHumanStatusAttribute()
    {
        return static::statusList()[$this->status];
    }

    public function getLabelStatusAttribute()
    {
        return static::statusLabel()[$this->status];
    }

    public static function allowedStatus()
    {
        return array_keys(static::statusList());
    }

    public function outlet() {
        return $this->belongsTo('App\Outlet', 'outlet_id');
    }
}

mainfile_hogwartz/resources/views/admin/contactus/index.blade.php
@extends('layouts.back')

@section('custom-css')
    <link href="{{ asset('assets/back/global/plugins/datatables/datatables.min.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('assets/back/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('assets/sweet-alert/sweetalert.css') }}" rel="stylesheet">
@endsection

@section('custom-js')
    <script src="{{ asset('assets/back/global/scripts/datatable.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/back/global/plugins/datatables/datatables.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/back/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js') }}" type="text/javascript"></script>
    <script type="text/javascript">
        var TableDatatablesEditable = function () {

            var handleTable = function () {
                var table = $('#sample_editable_1');
                var oTable = table.dataTable({
                    "responsive": true,
                    "lengthMenu": [
                        [5, 10, 15, 20, -1],
                        [5, 10, 15, 20, "All"] // change per page values here
                    ],

                    // set the initial value
                    "pageLength": 10,

                    "language": {
                        "lengthMenu": " _MENU_ records"
                    },
                    "columnDefs": [{ // set default column settings
                        'orderable': true,
                        'targets': [0]
                    }, {
                        "searchable": true,
                        "targets": [0]
                    }],
                    "order": [
                        [0, "asc"]
                    ] // set first column as a default sort by asc
                });

                var tableWrapper = $("#sample_editable_1_wrapper");
            }

            return {
                //main function to initiate the module
                init: function () {
                    handleTable();
                }

            };

        }();

        jQuery(document).ready(function() {
            TableDatatablesEditable.init();
        });
    </script>
    <script src="{{ asset('assets/sweet-alert/sweetalert.min.js') }}"></script>
    <script>
        $(document).ready(function () {
            $(document.body).on('click', '.js-submit-confirm', function (event) {
                event.preventDefault()
                var $form = $(this).closest('form')
                swal({
                            title: "Are you sure?",
                            text: "You can not undo this process!",
                            type: "warning",
                            showCancelButton: true,
                            confirmButtonColor: '#DD6B55',
                            confirmButtonText: 'Yes, delete it!',
                            cancelButtonText: "Cancel",
                            closeOnConfirm: true
                        },
                        function () {
                            $form.submit()
                        });
            })

            $(document.body).on('click', '.js-confirm', function (event) {
                event.preventDefault()
                var $form = $(this).closest('form')
                swal({
                            title: "Are you sure?",
                            text: "You can not undo this process!",
                            type: "warning",
                            showCancelButton: true,
                            confirmButtonColor: '#3598dc',
                            confirmButtonText: 'Yes, confirm it!',
                            cancelButtonText: "Cancel",
                            closeOnConfirm: true
                        },
                        function () {
                            $form.submit()
                        });
            })
        })
    </script>
@endsection

@section('page-heading')
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <span>Contact Messages</span>
            </li>
        </ul>
    </div>
    <h3 class="page-title"> Contact Messages</h3>
@endsection

@section('conten')
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN EXAMPLE TABLE PORTLET-->
            <div class="portlet light bordered">
                <div class="portlet-title">
                    <div class="caption font-dark">
                        <span class="caption-subject bold uppercase"> Contact Messages</span>
                    </div>

                </div>
                <div class="portlet-body">
                    <table class="table table-striped table-hover table-bordered" id="sample_editable_1">
                        <thead>
                        <tr>
                            <td>Name</td>
                            <td>Email</td>
                            <td>Phone</td>
                            <td>Subject</td>
                            <td class="none">Messages</td>
                            <td class="col-md-2">Status</td>
                            <td class="text-center col-md-1">#</td>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($messages as $message)
                            <tr>
                                <td>{{ $message->name }}</td>
                                <td>{{ $message->email }}</td>
                                <td>{{ $message->phone }}</td>
                                <td>{{ $message->subject }}</td>
                                <td>
                                    <p>{{ $message->message }}</p>
                                </td>
                                <td>
                                    <span class="label {{ $message->label_status }}">{{ $message->human_status }}</span>
                                </td>
                                <td class="text-center col-md-2 col-sm-3">
                                    <span class="tooltips" data-original-title="Delete" style="display: inline;">
                                        {!! Form::model($message, ['route' => ['contact-messages.destroy', $message], 'method' => 'delete', 'class' => 'form-inline', 'style' => 'display: inline; margin: 0; padding: 0;'] ) !!}
                                        {!! Form::button('<i class="fa fa-times"></i>', ['type' => 'submit', 'class'=>'btn btn btn-danger js-submit-confirm']) !!}
                                        {!! Form::close()!!}
                                    </span>
                                    @if($message->status == 'waiting-confirmation')
                                    <span class="tooltips" data-original-title="Mark as Confirmed" style="display: inline;">
                                        {!! Form::open(['route' => 'contact-messages.confirm', 'style' => 'display: inline; margin: 0; padding: 0;'])!!}
                                        {!! Form::hidden('contact_id', $message->id) !!}
                                        {!! Form::button('<i class="fa fa-thumbs-o-up"></i>', ['type' => 'submit', 'class'=>'btn btn btn-info js-confirm']) !!}
                                        {!! Form::close()!!}
                                    </span>
                                    @endif
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
            <!-- END EXAMPLE TABLE PORTLET-->
        </div>
    </div>
@endsection